version: '2'


networks:
  network:
    driver: bridge
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: clickhouse
      # MB_DB_DBNAME: metabaseappdb
      # MB_DB_PORT: 8123
      # MB_DB_USER: default
      # MB_DB_PASS: ''
      # MB_DB_HOST: clickhouse
    networks:
      - network
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5