version: '3'


networks:
  network:
    driver: bridge
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./services/metabase-plugins:/plugins
    ports:
      - 3000:3000
    networks:
      - network
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5